---
# Tasks to install required packages for EL distros
- name: Install playbook dependencies
  yum:
    name: '{{ item }}'
    state: present
    disable_gpg_check: '{{not gpgcheck|bool}}'
  with_items: "{{ el_dependencies }}"

- name: Enable required dnf modules
  shell: |
    dnf module -y enable {{ item }}
  args:
    warn: false
  with_items: "{{ dnf_modules }}"
