---
- name: Install postgres
  yum:
    name: "{{ item }}"
    enablerepo: "{{ ansible_tower_dependency_repo }}"
    disable_gpg_check: '{{ not gpgcheck | bool }}'
    state: present
  with_items: "{{ postgresql_packages }}"
